### ISSUE TITLE
English version links to pages in French language + 1 suggestion

### ISSUE THREAD

**Issue by Marina835** [TYPO3-Documentation/TYPO3CMS-Tutorial-Editors#5]
Hi there,

While reading the Editors Tutorial I found some links that don't seem right:

The 'Getting Started Tutorial' link in these pages:

https://docs.typo3.org/typo3cms/EditorsTutorial/Introduction/Index.html
https://docs.typo3.org/typo3cms/EditorsTutorial/ContentElements/Content/Index.html
https://docs.typo3.org/typo3cms/EditorsTutorial/ContentElements/Images/Index.html
https://docs.typo3.org/typo3cms/EditorsTutorial/Pages/WorkingWithPages/Index.html

lead to this 404-page:
https://docs.typo3.org/typo3cms/GettingStartedTutorial/fr_FR/Index.html#start

I suppose this is the correct link:
https://docs.typo3.org/typo3cms/GettingStartedTutorial/

On this page (English language) about the RTE: https://docs.typo3.org/typo3cms/EditorsTutorial/ContentElements/CreatingContent/Index.html
The link 'described in more details later' leads to a page in the French language... Mon Dieu!

On this page (in English):
https://docs.typo3.org/typo3cms/EditorsTutorial/Pages/CreatingPages/Index.html

the link 'Page type chapter'leads to a French page (https://docs.typo3.org/typo3cms/EditorsTutorial/fr_FR/Pages/PageTypes/Index.html#pages-types)
Also, the link 'mountpoints' on this page: https://docs.typo3.org/typo3cms/EditorsTutorial/Pages/PageProperties/Index.html, leads to a page in the French language.
I suppose this is the correct link in both cases: https://docs.typo3.org/typo3cms/EditorsTutorial/Pages/PageTypes/Index.html

The link 'content element type' on this page: https://docs.typo3.org/typo3cms/EditorsTutorial/Pages/PageProperties/Index.html also leads to a French text.
I suppose this is the correct link: https://docs.typo3.org/typo3cms/EditorsTutorial/ContentElements/CreatingContent/Index.html
On the same page the link 'mountpoints' also leads to a page in the French language. I suppose it should link to: 
https://docs.typo3.org/typo3cms/EditorsTutorial/Pages/PageTypes/Index.html

Also on the page https://docs.typo3.org/typo3cms/EditorsTutorial/Pages/CreatingPages/Index.html
I found an other link to a site in the French language:
'Page properties chapter' links to: https://docs.typo3.org/typo3cms/EditorsTutorial/fr_FR/Pages/PageProperties/Index.html#pages-properties
I suppose it should link to:
https://docs.typo3.org/typo3cms/EditorsTutorial/Pages/PageProperties/Index.html

The link 'page properties' on this page also leads to a French text:
https://docs.typo3.org/typo3cms/EditorsTutorial/Pages/PageTypes/Index.html

An other thing: 
I guess it would really help new users to see the icons depicted right in front of the page-types on this page (so they can connect the icons they can choose from to to the page types):
https://docs.typo3.org/typo3cms/EditorsTutorial/Pages/PageTypes/Index.html

**Comment by sypets** [comment]
@Marina835 Thanks for finding and reporting this. I am writing some more detailed technical information for others who may be reading as well. For now, just be assured we will take care of this.

I think, the problem is that the the entire manual has been copied to /fr_FR/, which duplicated the heading labels (e.g. label "introduction") that are used to automatically generate links to cross-reference. Example: in all manuals we use "start" or we use for example "introduction" as header labels. This can then be used to reference to the manual, e.g. `:ref:`introduction`. This label should be used unique for every manual, for this one it exists twice in English and French version, so we get unexpected results when links are created (with intersphinx link mechanism).

Example, see https://docs.typo3.org/typo3cms/EditorsTutorial/fr_FR/Index.html#start or [source](https://docs.typo3.org/typo3cms/EditorsTutorial/_sources/fr_FR/Index.txt)

**Comment by sypets** [comment]
Proposal:

* Move French version to separate branch
* Long term: find solution for other languages, see https://github.com/TYPO3-Documentation/T3DocTeam/issues/47

**Comment by sypets** [comment]
@Marina835 The problem with the links to French version should now be ok. I'll also check the other ones.

**Comment by sypets** [comment]
@Marina835  I checked all the pages and links you listed. Looks ok now. Again, thank you and sorry it took a while. For your last point, you might want to open a new issues, since this is unrelated. Also, if you can you might want to make the change you propose yourself (e.g. add small screenshot images).  

For more help, see [Writing Documentation: Contribute to docs.typo3.org](https://docs.typo3.org/typo3cms/HowToDocument/WritingDocsOfficial/Index.html and [Writing Documentation: How you can help](https://docs.typo3.org/typo3cms/HowToDocument/WritingDocsOfficial/HowYouCanHelp.html)
